// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rentacar.Data.EF;

namespace Rentacar.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rentacar.Data.Models.Komentari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AutorId");

                    b.Property<DateTime>("Datum_objave");

                    b.Property<string>("Sadrzaj");

                    b.Property<int?>("vijestId");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("vijestId");

                    b.ToTable("Komentaris");
                });

            modelBuilder.Entity("Rentacar.Data.Models.Korisnici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa");

                    b.Property<string>("Broj_telefona");

                    b.Property<DateTime>("Datum_rodjenja");

                    b.Property<string>("Email");

                    b.Property<string>("Ime");

                    b.Property<float>("Ostvareni_popust");

                    b.Property<string>("Prezime");

                    b.HasKey("Id");

                    b.ToTable("Korisnicis");
                });

            modelBuilder.Entity("Rentacar.Data.Models.Korisnicki_nalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Datum_prijave");

                    b.Property<int?>("KorisnikId");

                    b.Property<string>("Korsnicko_ime");

                    b.Property<string>("Lozinka");

                    b.Property<int?>("TipId");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("TipId");

                    b.ToTable("Korisnicki_nalogs");
                });

            modelBuilder.Entity("Rentacar.Data.Models.Permisije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv");

                    b.Property<int?>("Tipovi_korisnickog_nalogaId");

                    b.HasKey("Id");

                    b.HasIndex("Tipovi_korisnickog_nalogaId");

                    b.ToTable("Permisije");
                });

            modelBuilder.Entity("Rentacar.Data.Models.Tipovi_korisnickog_naloga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv");

                    b.Property<string>("Opis");

                    b.HasKey("Id");

                    b.ToTable("Tipovi_korisnickog_nalogas");
                });

            modelBuilder.Entity("Rentacar.Data.Models.Vijesti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AutorId");

                    b.Property<DateTime>("Datum_i_vrijeme_objave");

                    b.Property<string>("Naslov");

                    b.Property<string>("Sadrzaj");

                    b.Property<string>("Slika");

                    b.Property<string>("URL");

                    b.Property<int>("Ukupno_pregleda");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Vijestis");
                });

            modelBuilder.Entity("Rentacar.Data.Models.Komentari", b =>
                {
                    b.HasOne("Rentacar.Data.Models.Korisnicki_nalog", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId");

                    b.HasOne("Rentacar.Data.Models.Vijesti", "vijest")
                        .WithMany()
                        .HasForeignKey("vijestId");
                });

            modelBuilder.Entity("Rentacar.Data.Models.Korisnicki_nalog", b =>
                {
                    b.HasOne("Rentacar.Data.Models.Korisnici", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId");

                    b.HasOne("Rentacar.Data.Models.Tipovi_korisnickog_naloga", "Tip")
                        .WithMany()
                        .HasForeignKey("TipId");
                });

            modelBuilder.Entity("Rentacar.Data.Models.Permisije", b =>
                {
                    b.HasOne("Rentacar.Data.Models.Tipovi_korisnickog_naloga")
                        .WithMany("Permisije")
                        .HasForeignKey("Tipovi_korisnickog_nalogaId");
                });

            modelBuilder.Entity("Rentacar.Data.Models.Vijesti", b =>
                {
                    b.HasOne("Rentacar.Data.Models.Korisnicki_nalog", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId");
                });
#pragma warning restore 612, 618
        }
    }
}
